### ISSUE TITLE
Error 500 - possibly related to a partitioned server

### ISSUE THREAD

**Issue by seancull** [majkilde/LogFileReader#2]
Installed as per instructions on 9.01 FP4 behined https but throws an error 500 in the browser and the log messages below

works fine on a non partitioned server of similar build. Is the issue that thepartioned server uses a different directory structure ?

######

Out of memory exception occurred servicing request for: /xxxxx.nsf/Reader.xsp 

#######

	<extendedDataElements name="CommonBaseEventLogRecord:Exception" type="string">
		<values>java.lang.OutOfMemoryError: Java heap space&#xA;&#x9;at java.lang.StringBuilder.ensureCapacityImpl(StringBuilder.java:342)&#xA;&#x9;at java.lang.StringBuilder.append(StringBuilder.java:208)&#xA;&#x9;at java.lang.StringBuilder.append(StringBuilder.java:194)&#xA;&#x9;at dk.xpages.utils.NotesStrings.join(NotesStrings.java:72)&#xA;&#x9;at dk.xpages.utils.NotesStrings.join(NotesStrings.java:86)&#xA;&#x9;at dk.majkilde.logreader.files.TextFile.getHtml(TextFile.java:70)&#xA;&#x9;at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#xA;&#x9;at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:60)&#xA;&#x9;at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:37)&#xA;&#x9;at java.lang.reflect.Method.invoke(Method.java:611)&#xA;&#x9;at com.ibm.jscript.types.JavaAccessObject.call(JavaAccessObject.java:321)&#xA;&#x9;at com.ibm.jscript.types.FBSObject.call(FBSObject.java:161)&#xA;&#x9;at com.ibm.jscript.ASTTree.ASTCall.interpret(ASTCall.java:197)&#xA;&#x9;at</values>
		<values> com.ibm.jscript.ASTTree.ASTIf.interpret(ASTIf.java:85)&#xA;&#x9;at com.ibm.jscript.ASTTree.ASTProgram.interpret(ASTProgram.java:119)&#xA;&#x9;at com.ibm.jscript.ASTTree.ASTProgram.interpretEx(ASTProgram.java:139)&#xA;&#x9;at com.ibm.jscript.JSExpression._interpretExpression(JSExpression.java:435)&#xA;&#x9;at com.ibm.jscript.JSExpression.access$1(JSExpression.java:424)&#xA;&#x9;at com.ibm.jscript.JSExpression$2.run(JSExpression.java:414)&#xA;&#x9;at java.security.AccessController.doPrivileged(AccessController.java:448)&#xA;&#x9;at com.ibm.jscript.JSExpression.interpretExpression(JSExpression.java:410)&#xA;&#x9;at com.ibm.jscript.JSExpression.evaluateValue(JSExpression.java:251)&#xA;&#x9;at com.ibm.jscript.JSExpression.evaluateValue(JSExpression.java:234)&#xA;&#x9;at com.ibm.xsp.javascript.JavaScriptInterpreter.interpret(JavaScriptInterpreter.java:222)&#xA;&#x9;at com.ibm.xsp.javascript.JavaScriptInterpreter.interpret(JavaScriptInterpreter.java:194)&#xA;&#x9;at com.ibm.xsp.binding.javascript.JavaScriptValueBind</values>
		<values>ing.getValue(JavaScriptValueBinding.java:78)&#xA;&#x9;at javax.faces.component.UIOutput.getValue(UIOutput.java:159)&#xA;&#x9;at com.ibm.xsp.util.FacesUtil.convertValue(FacesUtil.java:1122)&#xA;&#x9;at com.ibm.xsp.renderkit.html_basic.OutputTextRenderer.encodeEnd(OutputTextRenderer.java:97)&#xA;&#x9;at com.ibm.xsp.renderkit.ReadOnlyAdapterRenderer.encodeEnd(ReadOnlyAdapterRenderer.java:180)&#xA;&#x9;at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:1005)&#xA;&#x9;at com.ibm.xsp.util.FacesUtil.renderComponent(FacesUtil.java:858)&#xA;&#x9;at com.ibm.xsp.util.FacesUtil.renderComponent(FacesUtil.java:853)&#xA;&#x9;at com.ibm.xsp.util.FacesUtil.renderComponent(FacesUtil.java:853)&#xA;&#x9;at com.ibm.xsp.util.FacesUtil.renderComponent(FacesUtil.java:853)&#xA;&#x9;at com.ibm.xsp.util.FacesUtil.renderComponent(FacesUtil.java:853)&#xA;&#x9;at com.ibm.xsp.util.FacesUtil.renderComponent(FacesUtil.java:853)&#xA;&#x9;at com.ibm.xsp.util.FacesUtil.renderComponent(FacesUtil.java:853)&#xA;&#x9;at com.ibm.</values>
		<values>xsp.util.FacesUtil.renderComponent(FacesUtil.java:853)&#xA;&#x9;at com.ibm.xsp.util.FacesUtil.renderComponent(FacesUtil.java:853)&#xA;&#x9;at com.ibm.xsp.util.FacesUtil.renderComponent(FacesUtil.java:853)&#xA;&#x9;at com.ibm.xsp.util.FacesUtil.renderComponent(FacesUtil.java:853)&#xA;&#x9;at com.ibm.xsp.util.FacesUtil.renderComponent(FacesUtil.java:853)&#xA;&#x9;at com.ibm.xsp.util.FacesUtil.renderComponent(FacesUtil.java:853)&#xA;&#x9;at com.ibm.xsp.component.UIViewRootEx._renderView(UIViewRootEx.java:1317)&#xA;&#x9;at com.ibm.xsp.component.UIViewRootEx.renderView(UIViewRootEx.java:1255)&#xA;&#x9;at com.ibm.xsp.application.ViewHandlerExImpl.doRender(ViewHandlerExImpl.java:651)&#xA;&#x9;at com.ibm.xsp.application.ViewHandlerExImpl._renderView(ViewHandlerExImpl.java:321)&#xA;&#x9;at com.ibm.xsp.application.ViewHandlerExImpl.renderView(ViewHandlerExImpl.java:336)&#xA;&#x9;at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:103)&#xA;&#x9;at com.sun.faces.lifecycle.LifecycleImpl.phase(Li</values>
		<values>fecycleImpl.java:210)&#xA;&#x9;at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:120)&#xA;&#x9;at com.ibm.xsp.controller.FacesControllerImpl.render(FacesControllerImpl.java:270)&#xA;&#x9;at com.ibm.xsp.webapp.FacesServlet.serviceView(FacesServlet.java:261)&#xA;&#x9;at com.ibm.xsp.webapp.FacesServletEx.serviceView(FacesServletEx.java:157)&#xA;&#x9;at com.ibm.xsp.webapp.FacesServlet.service(FacesServlet.java:160)&#xA;&#x9;at com.ibm.xsp.webapp.FacesServletEx.service(FacesServletEx.java:138)&#xA;&#x9;at com.ibm.xsp.webapp.DesignerFacesServlet.service(DesignerFacesServlet.java:103)&#xA;&#x9;at com.ibm.designer.runtime.domino.adapter.ComponentModule.invokeServlet(ComponentModule.java:576)&#xA;&#x9;at com.ibm.domino.xsp.module.nsf.NSFComponentModule.invokeServlet(NSFComponentModule.java:1335)&#xA;&#x9;at com.ibm.designer.runtime.domino.adapter.ComponentModule$AdapterInvoker.invokeServlet(ComponentModule.java:853)&#xA;&#x9;at com.ibm.designer.runtime.domino.adapter.ComponentModule$ServletInvoker.doSe</values>
		<values>rvice(ComponentModule.java:796)&#xA;&#x9;at com.ibm.designer.runtime.domino.adapter.ComponentModule.doService(ComponentModule.java:565)&#xA;&#x9;at com.ibm.domino.xsp.module.nsf.NSFComponentModule.doService(NSFComponentModule.java:1319)&#xA;&#x9;at com.ibm.domino.xsp.module.nsf.NSFService.doServiceInternal(NSFService.java:662)&#xA;&#x9;at com.ibm.domino.xsp.module.nsf.NSFService.doService(NSFService.java:482)&#xA;&#x9;at com.ibm.designer.runtime.domino.adapter.LCDEnvironment.doService(LCDEnvironment.java:357)&#xA;&#x9;at com.ibm.designer.runtime.domino.adapter.LCDEnvironment.service(LCDEnvironment.java:313)&#xA;&#x9;at com.ibm.domino.xsp.bridge.http.engine.XspCmdManager.service(XspCmdManager.java:272)&#xA;</values>
	</extendedDataElements>

**Comment by seancull** [comment]
p.s. I had already removed the reference in config.xml to openlog

**Comment by seancull** [comment]
Works fine after pasting in default config.xml ( from the help document )  - not sure what the issue was.
The default config.xml ( as in the one supplied as an attachement in the setup help document ) does not refer to open log and has some other differences

**Comment by seancull** [comment]
have added pull request to modify project - https://github.com/issues?q=is%3Apr+is%3Aopen
